// Package coredump is CTP's core analyzer: what it asks gdb, and what it makes
// of the answer.
//
// CQT writes one file per case that dumped core -- <case>.err beside the
// case's failure copies -- and that file is a reader's first look at a crash.
// It is CTP's common/coreanalyzer (Analyzer, AnalyzerMain.fetchCoreFullStack)
// and ConsoleBO.saveCoreCallStackFile, transcribed: the same two gdb
// invocations, the same way of cutting the stack out of gdb's output, and the
// same one-line summary.
//
// Nothing here parses a core file. It runs gdb, exactly as CTP does, and reads
// its text -- so what a .err holds depends on the machine's gdb and on whether
// the binary has symbols, as it always has.
package coredump

import (
	"context"
	"fmt"
	"io"
	"strings"

	"github.com/cubrid-systems/cubrid-testkit/internal/exec"
)

// Stack is one core, analyzed.
type Stack struct {
	// Core is the file, as it was found.
	Core string
	// Process is the program that dumped it: cub_server, cub_cas, csql,
	// cubrid, cub_admin, or whatever name the core names.
	Process string
	// Summary is one line -- "Core dumped in <function> at src/..." -- taken
	// from the innermost frame in CUBRID's own source. It is empty when no
	// frame is, which is what a core with no symbols gives.
	Summary string
	// Detail is gdb's `bt full`, as printed.
	Detail string
}

// Analyze is AnalyzerMain.fetchCoreFullStack: name the process, then ask gdb
// for the whole stack.
//
// It runs where the core is. A slot's core, its $CUBRID and the cub_server
// that dumped it are all inside that slot, so the channel has to be the
// slot's.
func Analyze(ctx context.Context, ch exec.Channel, core string) (Stack, error) {
	s := Stack{Core: core}
	name, err := process(ctx, ch, core)
	if err != nil {
		return s, err
	}
	s.Process = name

	// CTP's own here-document, which is why a gdb that cannot open the core
	// still exits 0 with its complaint in the output.
	res, err := ch.Run(ctx, "gdb `which "+name+"` "+exec.Quote(core)+" <<'EOF'\nbt full\nEOF")
	if err != nil {
		return s, err
	}
	s.Detail = betweenPrompts(res.Output())
	if s.Detail == "" {
		return s, fmt.Errorf("gdb printed no stack for %s", core)
	}
	s.Summary = summarize(s.Detail)
	return s, nil
}

// process is Analyzer's two attempts at the program's name: file(1) first,
// then gdb's own line, and an error when neither says.
func process(ctx context.Context, ch exec.Channel, core string) (string, error) {
	if res, err := ch.Run(ctx, "file "+exec.Quote(core)); err == nil {
		if name := nameFromFile(res.Output()); name != "" {
			return name, nil
		}
	}
	res, err := ch.Run(ctx, "gdb "+exec.Quote(core)+" -ex 'quit' 2>/dev/null | grep 'Core was generated by'")
	if err != nil {
		return "", err
	}
	if name := nameFromGdb(res.Output()); name != "" {
		return name, nil
	}
	return "", fmt.Errorf("cannot tell what program dumped %s", core)
}

// nameFromFile reads file(1): "…core file …, from 'cub_server testdb'".
func nameFromFile(desc string) string { return quoted(desc, "from '", "'") }

// nameFromGdb reads gdb's "Core was generated by `cub_server testdb'."
func nameFromGdb(desc string) string { return quoted(desc, "by `", "'") }

func quoted(desc, open, close string) string {
	at := strings.Index(desc, open)
	if at == -1 {
		return ""
	}
	rest := desc[at+len(open):]
	if end := strings.Index(rest, close); end != -1 {
		rest = rest[:end]
	}
	return mapName(rest)
}

// mapName is Analyzer.extractCoreProcessName: the command line a core names is
// not always the binary gdb should be given.
func mapName(cmdline string) string {
	switch {
	case strings.Contains(cmdline, "cub_cas"):
		return "cub_cas"
	case strings.Contains(cmdline, "cub_server"):
		return "cub_server"
	case strings.Contains(cmdline, "cubrid "):
		// `cubrid server start x` is the utility; `cubrid <anything else>` is
		// the administrator.
		for _, sub := range []string{" service", " server", " broker", " manager", " heartbeat", " hb"} {
			if strings.Contains(cmdline, sub) {
				return "cubrid"
			}
		}
		return "cub_admin"
	case strings.Contains(cmdline, "csql"):
		return "csql"
	default:
		return strings.TrimSpace(strings.SplitN(cmdline, " ", 2)[0])
	}
}

// betweenPrompts is Analyzer.extractCoreStack: the stack is what gdb printed
// between its last two "(gdb)" prompts -- the one that invited `bt full` and
// the one that came after it.
func betweenPrompts(out string) string {
	const prompt = "(gdb)"
	last := strings.LastIndex(out, prompt)
	if last == -1 {
		return ""
	}
	before := strings.LastIndex(out[:last], prompt)
	if before == -1 {
		return ""
	}
	return strings.TrimSpace(out[before+len(prompt) : last])
}

// excluded are the frames a summary skips: every crash goes through the error
// machinery on its way out, and naming it would say nothing.
var excluded = map[string]bool{
	"er_log": true, "er_set_internal": true, "abort_handler": true, "er_set": true,
}

// summarize is Analyzer.extractCoreStackDigest's first half: the innermost
// frame in CUBRID's own source, by the file path gdb printed after "at".
func summarize(detail string) string {
	for _, f := range frames(detail) {
		if !strings.HasPrefix(f.file, "src/") || excluded[f.function] {
			continue
		}
		return "Core dumped in " + f.function + " at " + f.file
	}
	return ""
}

type frame struct{ function, file string }

// frames splits gdb's backtrace the way Analyzer does: on "#0", "#1", … in
// order, each frame flattened to one line first, so that `bt full`'s locals
// between two frames belong to the frame above them.
func frames(detail string) []frame {
	var out []frame
	end := 0
	for n := 0; ; n++ {
		start := strings.Index(detail[end:], "#"+itoa(n))
		if start == -1 {
			return out
		}
		start += end
		end = len(detail)
		if next := strings.Index(detail[start:], "#"+itoa(n+1)); next != -1 {
			end = start + next
		}
		if f, ok := parseFrame(detail[start:end]); ok {
			out = append(out, f)
		}
	}
}

// parseFrame reads one flattened frame. gdb writes it either as
//
//	#3  0x00007f… in pt_check_where (parser=0x…) at src/parser/semantic_check.c:1234
//
// or, with no address, as
//
//	#0  pt_check_where (parser=0x…) at src/…
//
// and for a frame with no source, "from /usr/lib/libc.so.6" instead of the
// "at". So the function is the first word unless that word is an address, and
// the file is the word after the first "at" or "from" -- the first, because an
// argument can be a string holding either word.
//
// A frame Analyzer cannot read at all it throws on, which loses the whole
// core; this one skips the frame. Only gdb output with a one-word frame in it
// tells the two apart.
func parseFrame(text string) (frame, bool) {
	text = strings.NewReplacer("\t", " ", "\n", " ", "\r", " ").Replace(text)
	words := strings.Fields(text)
	if len(words) < 2 {
		return frame{}, false
	}
	f := frame{function: words[1]}
	if strings.HasPrefix(f.function, "0x") {
		if len(words) < 4 {
			return frame{}, false
		}
		f.function = words[3]
	}
	for i, w := range words {
		if w == "at" || w == "from" {
			if i+1 < len(words) {
				f.file = words[i+1]
			}
			break
		}
	}
	// Analyzer keeps the path from the last "src/", so a build directory in
	// front of it does not reach the summary.
	if at := strings.LastIndex(f.file, "src/"); at != -1 {
		f.file = f.file[at:]
	}
	return f, true
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

// Report writes CQT's .err: a header naming every core, then each core's stack
// under a banner (ConsoleBO.saveCoreCallStackFile). coreDir is where the cores
// were left -- $CORE_BACKUP_DIR/<test id> when that is set, and $CUBRID
// otherwise.
//
// A core whose analysis failed is not in the file at all, header included,
// because CQT's loop only appends what fetchCoreFullStack returned.
func Report(w io.Writer, coreDir string, stacks []Stack) error {
	var head, body strings.Builder
	if len(stacks) > 0 {
		head.WriteString("SUMMARY:\n")
		head.WriteString("CORE_DIR:" + coreDir + "\n")
	}
	for _, s := range stacks {
		name := base(s.Core)
		head.WriteString(name + " [" + s.Process + "] " + s.Summary + "\n")
		body.WriteString("\n==================" + name + "==================\n")
		body.WriteString(s.Detail)
	}
	_, err := io.WriteString(w, head.String()+body.String())
	return err
}

// base is File.getName: everything after the last separator.
func base(path string) string {
	if at := strings.LastIndex(path, "/"); at != -1 {
		return path[at+1:]
	}
	return path
}
