package coredump

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	tkexec "github.com/cubrid-systems/cubrid-testkit/internal/exec"
)

func TestTheProgramACoreNames(t *testing.T) {
	for _, c := range []struct {
		what, desc, want string
	}{
		// file(1), which is what Analyzer asks first.
		{"a server", "core.27788: ELF 64-bit LSB core file x86-64, version 1 (SYSV), SVR4-style, from 'cub_server testdb'", "cub_server"},
		{"a broker", "core.1: ELF 64-bit LSB core file, from 'cub_cas_1 testdb'", "cub_cas"},
		{"csql", "core.2: ELF 64-bit LSB core file, from 'csql --sysadm testdb'", "csql"},
		// `cubrid` is the utility for the services it manages and the
		// administrator for everything else.
		{"the utility", "core.3: from 'cubrid server start testdb'", "cubrid"},
		{"the heartbeat", "core.4: from 'cubrid heartbeat start'", "cubrid"},
		{"the administrator", "core.5: from 'cubrid createdb demodb'", "cub_admin"},
		// Anything else is its own first word.
		{"something else", "core.6: from 'unknown_tool -x'", "unknown_tool"},
		{"an unterminated quote", "core.7: from 'cub_server", "cub_server"},
		{"not a core at all", "core.8: ASCII text", ""},
	} {
		if got := nameFromFile(c.desc); got != c.want {
			t.Errorf("%s: nameFromFile = %q, want %q", c.what, got, c.want)
		}
	}
	// gdb's own line, which Analyzer falls back to.
	if got := nameFromGdb("Core was generated by `cub_server testdb'."); got != "cub_server" {
		t.Errorf("nameFromGdb = %q, want cub_server", got)
	}
	if got := nameFromGdb("no such line"); got != "" {
		t.Errorf("nameFromGdb = %q, want empty", got)
	}
}

// gdb prints a prompt before it reads each command and once more when the
// here-document ends, so the stack is what lies between the last two.
func TestTheStackIsWhatLiesBetweenTheLastTwoPrompts(t *testing.T) {
	out := "GNU gdb 15.0\nReading symbols...\n" +
		"Core was generated by `cub_server testdb'.\n" +
		"(gdb) #0  0x00 in a () at src/a.c:1\n#1  0x00 in b () at src/b.c:2\n" +
		"(gdb) quit\n"
	want := "#0  0x00 in a () at src/a.c:1\n#1  0x00 in b () at src/b.c:2"
	if got := betweenPrompts(out); got != want {
		t.Errorf("betweenPrompts = %q, want %q", got, want)
	}
	for _, c := range []string{"", "no prompt at all", "(gdb) only one"} {
		if got := betweenPrompts(c); got != "" {
			t.Errorf("betweenPrompts(%q) = %q, want empty", c, got)
		}
	}
}

// The summary names the innermost frame in CUBRID's own source: not the signal
// handler above it, not the C library below.
func TestTheSummaryIsTheInnermostFrameInCUBRIDsSource(t *testing.T) {
	detail := `#0  0x00007f1f in __pthread_kill_implementation () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007f1f in abort_handler (signo=11) at src/base/error_manager.c:2310
        er_msg = 0x0
#2  <signal handler called>
#3  0x000055a1 in er_set (severity=1, file_name=0x7f1f "x") at src/base/error_manager.c:1120
No locals.
#4  0x000055a1 in pt_check_where (parser=0x7f1e, node=0x0) at /build/cubrid/src/parser/semantic_check.c:9814
        arg1 = 0x0
        arg2 = 0x0
#5  0x000055a1 in main () at src/executables/csql.c:1
No locals.
`
	// #0 is the library, #1 and #3 are the error machinery, #4 is the answer --
	// and its path keeps only what follows the last "src/".
	if got := summarize(detail); got != "Core dumped in pt_check_where at src/parser/semantic_check.c:9814" {
		t.Errorf("summarize = %q", got)
	}

	// A core with no symbols has no frame in src/ and so no summary, which
	// leaves the header line ending in the process name.
	none := "#0  0x00007f1f in ?? () from /lib/x86_64-linux-gnu/libc.so.6\n#1  0x00 in ?? ()\n"
	if got := summarize(none); got != "" {
		t.Errorf("summarize of a stripped core = %q, want empty", got)
	}
}

// A frame's function is the first word after the number unless that word is an
// address, and its file is what follows the first "at" or "from".
func TestAFrameIsReadTheWayAnalyzerReadsIt(t *testing.T) {
	for _, c := range []struct{ text, fn, file string }{
		{"#0  pt_check_where (p=0x0) at src/parser/semantic_check.c:1", "pt_check_where", "src/parser/semantic_check.c:1"},
		{"#3  0x00007f in pt_check_where (p=0x0) at src/parser/semantic_check.c:1", "pt_check_where", "src/parser/semantic_check.c:1"},
		{"#1  0x00007f in __kill () from /lib/libc.so.6", "__kill", "/lib/libc.so.6"},
		// Analyzer splits a frame on spaces and takes the word after the
		// first "at", so an argument that contains the word wins over the
		// frame's own. Kept, because the file it gives does not start with
		// "src/" and the effect is only that such a frame is not the summary.
		{"#2  0x00 in f (msg=0x7f \"look at this\") at src/a.c:9", "f", "this\")"},
		// `bt full`'s locals follow the frame and are flattened into it; the
		// file was already taken from the frame's own "at".
		{"#4  0x00 in g () at src/b.c:3\n        local = 0x0\n        other = 1", "g", "src/b.c:3"},
	} {
		got, ok := parseFrame(c.text)
		if !ok || got.function != c.fn || got.file != c.file {
			t.Errorf("parseFrame(%q) = %+v (%t); want %s at %s", c.text, got, ok, c.fn, c.file)
		}
	}
	if _, ok := parseFrame("#0"); ok {
		t.Error("a frame with nothing after its number should be skipped")
	}
}

// The layout is ConsoleBO.saveCoreCallStackFile's: a header naming every core,
// then one banner and one stack per core.
func TestTheReportIsCQTsLayout(t *testing.T) {
	var b bytes.Buffer
	if err := Report(&b, "/home/q/CUBRID", []Stack{
		{Core: "/home/q/CUBRID/core.100", Process: "cub_server", Summary: "Core dumped in f at src/a.c:1", Detail: "#0  f ()"},
		{Core: "/home/q/CUBRID/core.200", Process: "cub_cas", Summary: "", Detail: "#0  g ()"},
	}); err != nil {
		t.Fatal(err)
	}
	want := "SUMMARY:\n" +
		"CORE_DIR:/home/q/CUBRID\n" +
		"core.100 [cub_server] Core dumped in f at src/a.c:1\n" +
		"core.200 [cub_cas] \n" +
		"\n==================core.100==================\n#0  f ()" +
		"\n==================core.200==================\n#0  g ()"
	if b.String() != want {
		t.Errorf("the report was\n%q\nwant\n%q", b.String(), want)
	}

	// No core, no file: CQT writes neither header when the list is empty.
	b.Reset()
	if err := Report(&b, "/home/q/CUBRID", nil); err != nil || b.Len() != 0 {
		t.Errorf("an empty report wrote %q (%v)", b.String(), err)
	}
}

// Analyze against a core this test makes, because every step before the
// parsing -- file(1), `which`, the here-document, gdb's prompts -- is only
// real against a real core.
func TestAnalyzeReadsARealCore(t *testing.T) {
	for _, tool := range []string{"gdb", "gcore", "file", "sleep"} {
		if _, err := exec.LookPath(tool); err != nil {
			t.Skipf("%s is not on this machine", tool)
		}
	}
	dir := t.TempDir()
	sleep, err := exec.LookPath("sleep")
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(sleep, "300")
	if err := cmd.Start(); err != nil {
		t.Fatal(err)
	}
	defer func() {
		cmd.Process.Kill()
		cmd.Wait()
	}()

	// gcore writes a core without waiting for a crash, and without depending
	// on this machine's core_pattern.
	out, err := exec.Command("gcore", "-o", filepath.Join(dir, "core"), itoa(cmd.Process.Pid)).CombinedOutput()
	if err != nil {
		t.Skipf("gcore could not take a core here: %v\n%s", err, out)
	}
	entries, err := os.ReadDir(dir)
	if err != nil || len(entries) == 0 {
		t.Skipf("gcore wrote nothing: %v", err)
	}
	core := filepath.Join(dir, entries[0].Name())

	s, err := Analyze(t.Context(), tkexec.NewLocal(""), core)
	if err != nil {
		t.Fatalf("Analyze(%s): %v", core, err)
	}
	// The core names the command line as it was run, which is not one of
	// CUBRID's programs, so the name is its first word -- the path this test
	// started it by.
	if !strings.HasSuffix(s.Process, "sleep") {
		t.Errorf("the process was %q, want something ending in sleep", s.Process)
	}
	// Whatever the frames are on this machine, gdb's backtrace starts at #0
	// and the prompts have been cut off it.
	if !strings.HasPrefix(s.Detail, "#0") {
		t.Errorf("the stack does not start at #0:\n%s", s.Detail)
	}
	if strings.Contains(s.Detail, "(gdb)") {
		t.Errorf("a prompt is still in the stack:\n%s", s.Detail)
	}
	// sleep is not built from CUBRID's source, so there is no summary -- the
	// same as a CUBRID core with no symbols.
	if s.Summary != "" {
		t.Errorf("summary of a core outside CUBRID's source: %q", s.Summary)
	}
}
